### ISSUE TITLE
请问，目前这个provider支持华为私有云吗？

### ISSUE THREAD

**Issue by scarecrow111** [huaweicloud/terraform-provider-hcs#1]
### Current Terraform Version

```
...
```

**Comment by iskey** [comment]
支持HCS 8.3.0版本

**Comment by scarecrow111** [comment]
> 支持HCS 8.3.0版本，预计9月30号会发布正式版本，请到时选用最新发布版本
> 
> https://github.com/huaweicloud/terraform-provider-hcs#compatibility-with-hcs:~:text=the%20provider%20plugin)-,Compatibility,-with%20HCS

Thx.
